var input = [
  {
    slug: "Start",
    text: "Who is the gift for?",
    connectsto: "her~ him",
    connectstext: "<img src='https://picsum.photos/seed/her/200/200' width='100%' />~ <img src='https://picsum.photos/seed/him/200/200' width='100%' />", 
    toolTipText: "Her~ Him",
    rowNumber: 1,
    nostoId: "", 
  },
  
  //For Her
  
  {
    slug: "her",
    text: "What role does she play in your heart?",
    connectsto: "her-love~ her-friend~ her-mother",
    connectstext: "<img src='https://picsum.photos/seed/love/200/200' width='100%' />~ <img src='https://picsum.photos/seed/friend/200/200' width='100%' />~ <img src='https://picsum.photos/seed/mother/200/200' width='100%' />",
    toolTipText: "My Love~ My friend~ My Mother",
    rowNumber: 2,
    nostoId: "",
  },
  
  //love
  
  {
    slug: "her-love",
    text: "What type of woman is she?",
    connectsto: "her-love-casual~ her-love-luxurious~ her-love-fashionable~ her-love-classic",
    connectstext: "<img src='https://picsum.photos/seed/casual/200/200' width='100%' />~ <img src='https://picsum.photos/seed/luxurious/200/200' width='100%' />~ <img src='https://picsum.photos/seed/fashionable/200/200' width='100%' />~ <img src='https://picsum.photos/seed/classic/200/200' width='100%' />",
    toolTipText: "Casual~ Luxurious~ Fashionable~ Classic",
    rowNumber: 3,
    nostoId: "",
  },
  {
    slug: "her-love-casual",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/diamonds/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />",
    toolTipText: "Jewellery~ Diamond Jewellery~ Jewellery~ Jewellery",
    rowNumber: 4,
    nostoId: "",
  },
  {
    slug: "her-love-luxurious",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/engagement/200/200' width='100%' />~ <img src='https://picsum.photos/seed/rings/200/200' width='100%' />~ <img src='https://picsum.photos/seed/ring/200/200' width='100%' />~ <img src='https://picsum.photos/seed/diamondrings/200/200' width='100%' />",
    toolTipText: "Engagement Rings~ Engagement Rings~ Engagement Rings~ Engagement Rings",
    rowNumber: 4,
    nostoId: "",
  },
  {
    slug: "her-love-fashionable",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/watch/200/200' width='100%' />~ <img src='https://picsum.photos/seed/watches/200/200' width='100%' />~ <img src='https://picsum.photos/seed/fashion/200/200' width='100%' />~ <img src='https://picsum.photos/seed/all/200/200' width='100%' />",
    toolTipText: "Fashion Watches~ Luxurius Watches~ Fashion Watches~ All Watches",
    rowNumber: 4,
    nostoId: "",
  },
  {
    slug: "her-love-classic",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />",
    toolTipText: "Inspire Me~ Inspire Me~ Inspire Me~ Inspire Me",
    rowNumber: 4,
    nostoId: "",
  },
  
  //friend
  
  {
    slug: "her-friend",
    text: "What type of woman is she?",
    connectsto: "her-friend-casual~ her-friend-luxurious~ her-friend-fashionable~ her-friend-classic",
    connectstext: "<img src='https://picsum.photos/seed/casual/200/200' width='100%' />~ <img src='https://picsum.photos/seed/luxurious/200/200' width='100%' />~ <img src='https://picsum.photos/seed/fashionable/200/200' width='100%' />~ <img src='https://picsum.photos/seed/classic/200/200' width='100%' />",
    toolTipText: "Casual~ Luxurious~ Fashionable~ Classic",
    rowNumber: 3,
    nostoId: "",
  },
  {
    slug: "her-friend-casual",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/diamonds/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />",
    toolTipText: "Earrings~ Diamond Jewellery~ Earrings~ Earrings",
    rowNumber: 4,
    nostoId: "",
  },
  {
    slug: "her-friend-luxurious",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/engagement/200/200' width='100%' />~ <img src='https://picsum.photos/seed/rings/200/200' width='100%' />~ <img src='https://picsum.photos/seed/ring/200/200' width='100%' />~ <img src='https://picsum.photos/seed/diamondrings/200/200' width='100%' />",
    toolTipText: "Pendants~ Jewellery Boards~ Pendants~ Pendants",
    rowNumber: 4,
    nostoId: "",
  },
  {
    slug: "her-friend-fashionable",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/watch/200/200' width='100%' />~ <img src='https://picsum.photos/seed/watches/200/200' width='100%' />~ <img src='https://picsum.photos/seed/fashion/200/200' width='100%' />~ <img src='https://picsum.photos/seed/all/200/200' width='100%' />",
    toolTipText: "Fashion Watches~ Luxurius Watches~ Fashion Watches~ All Watches",
    rowNumber: 4,
    nostoId: "",
  },
  {
    slug: "her-friend-classic",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />",
    toolTipText: "Inspire Me~ Inspire Me~ Inspire Me~ Inspire Me",
    rowNumber: 4,
    nostoId: "",
  },
  
  //mother
  
  {
    slug: "her-mother",
    text: "What type of woman is she?",
    connectsto: "her-mother-casual~ her-mother-luxurious~ her-mother-fashionable~ her-mother-classic",
    connectstext: "<img src='https://picsum.photos/seed/casual/200/200' width='100%' />~ <img src='https://picsum.photos/seed/luxurious/200/200' width='100%' />~ <img src='https://picsum.photos/seed/fashionable/200/200' width='100%' />~ <img src='https://picsum.photos/seed/classic/200/200' width='100%' />",
    toolTipText: "Casual~ Luxurious~ Fashionable~ Classic",
    rowNumber: 3,
    nostoId: "",
  },
  {
    slug: "her-mother-casual",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/diamonds/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />",
    toolTipText: "Earrings~ Diamond Jewellery~ Earrings~ Earrings",
    rowNumber: 4,
    nostoId: "",
  },
  {
    slug: "her-mother-luxurious",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/engagement/200/200' width='100%' />~ <img src='https://picsum.photos/seed/rings/200/200' width='100%' />~ <img src='https://picsum.photos/seed/ring/200/200' width='100%' />~ <img src='https://picsum.photos/seed/diamondrings/200/200' width='100%' />",
    toolTipText: "Pendants~ Jewellery Boards~ Pendants~ Pendants",
    rowNumber: 4,
    nostoId: "",
  },
  {
    slug: "her-mother-fashionable",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/watch/200/200' width='100%' />~ <img src='https://picsum.photos/seed/watches/200/200' width='100%' />~ <img src='https://picsum.photos/seed/fashion/200/200' width='100%' />~ <img src='https://picsum.photos/seed/all/200/200' width='100%' />",
    toolTipText: "Fashion Watches~ Luxurius Watches~ Fashion Watches~ All Watches",
    rowNumber: 4,
    nostoId: "",
  },
  {
    slug: "her-mother-classic",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />",
    toolTipText: "Inspire Me~ Inspire Me~ Inspire Me~ Inspire Me",
    rowNumber: 4,
    nostoId: "",
  },
  
  
  //For Him
  
  
  {
    slug: "him",
    text: "What role does he play in your heart?",
    connectsto: "him-love~ him-friend~ him-father",
    connectstext: "<img src='https://picsum.photos/seed/love/200/200' width='100%' />~ <img src='https://picsum.photos/seed/friend/200/200' width='100%' />~ <img src='https://picsum.photos/seed/father/200/200' width='100%' />",
    toolTipText: "My Love~ My friend~ My Father",
    rowNumber: 2,
    nostoId: "",
  },
  
  //love
  
  {
    slug: "him-love",
    text: "What type of man is he?",
    connectsto: "him-love-casual~ him-love-luxurious~ him-love-fashionable~ him-love-classic",
    connectstext: "<img src='https://picsum.photos/seed/casual/200/200' width='100%' />~ <img src='https://picsum.photos/seed/luxurious/200/200' width='100%' />~ <img src='https://picsum.photos/seed/fashionable/200/200' width='100%' />~ <img src='https://picsum.photos/seed/classic/200/200' width='100%' />",
    toolTipText: "Casual~ Luxurious~ Fashionable~ Classic",
    rowNumber: 3,
    nostoId: "",
  },
  {
    slug: "him-love-casual",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/diamonds/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />",
    toolTipText: "Jewellery~ Jewellery~ Jewellery~ Jewellery",
    rowNumber: 4,
    nostoId: "",
  },
  {
    slug: "him-love-luxurious",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/engagement/200/200' width='100%' />~ <img src='https://picsum.photos/seed/rings/200/200' width='100%' />~ <img src='https://picsum.photos/seed/ring/200/200' width='100%' />~ <img src='https://picsum.photos/seed/diamondrings/200/200' width='100%' />",
    toolTipText: "Fashion Watches~ Luxurius Watches~ Luxurius Watches~ Luxurius Watches",
    rowNumber: 4,
    nostoId: "",
  },
  {
    slug: "him-love-fashionable",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/watch/200/200' width='100%' />~ <img src='https://picsum.photos/seed/watches/200/200' width='100%' />~ <img src='https://picsum.photos/seed/fashion/200/200' width='100%' />~ <img src='https://picsum.photos/seed/all/200/200' width='100%' />",
    toolTipText: "Accessories~ Accessories~ Accessories~ Accessories",
    rowNumber: 4,
    nostoId: "",
  },
  {
    slug: "him-love-classic",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />",
    toolTipText: "Inspire Me~ Inspire Me~ Inspire Me~ Inspire Me",
    rowNumber: 4,
    nostoId: "",
  },
  
  //friend
  
  {
    slug: "him-friend",
    text: "What type of man is he?",
    connectsto: "him-friend-casual~ him-friend-luxurious~ him-friend-fashionable~ him-friend-classic",
    connectstext: "<img src='https://picsum.photos/seed/casual/200/200' width='100%' />~ <img src='https://picsum.photos/seed/luxurious/200/200' width='100%' />~ <img src='https://picsum.photos/seed/fashionable/200/200' width='100%' />~ <img src='https://picsum.photos/seed/classic/200/200' width='100%' />",
    toolTipText: "Casual~ Luxurious~ Fashionable~ Classic",
    rowNumber: 3,
    nostoId: "",
  },
  {
    slug: "him-friend-casual",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/diamonds/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />",
    toolTipText: "Jewellery~ Jewellery~ Jewellery~ Jewellery",
    rowNumber: 4,
    nostoId: "",
  },
  {
    slug: "him-friend-luxurious",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/engagement/200/200' width='100%' />~ <img src='https://picsum.photos/seed/rings/200/200' width='100%' />~ <img src='https://picsum.photos/seed/ring/200/200' width='100%' />~ <img src='https://picsum.photos/seed/diamondrings/200/200' width='100%' />",
    toolTipText: "Fashion Watches~ Luxurius Watches~ Luxurius Watches~ Luxurius Watches",
    rowNumber: 4,
    nostoId: "",
  },
  {
    slug: "him-friend-fashionable",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/watch/200/200' width='100%' />~ <img src='https://picsum.photos/seed/watches/200/200' width='100%' />~ <img src='https://picsum.photos/seed/fashion/200/200' width='100%' />~ <img src='https://picsum.photos/seed/all/200/200' width='100%' />",
    toolTipText: "Accessories~ Accessories~ Accessories~ Accessories",
    rowNumber: 4,
    nostoId: "",
  },
  {
    slug: "him-friend-classic",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />",
    toolTipText: "Inspire Me~ Inspire Me~ Inspire Me~ Inspire Me",
    rowNumber: 4,
    nostoId: "",
  },
  
  //father
  
  {
    slug: "him-father",
    text: "What type of man is he?",
    connectsto: "him-father-casual~ him-father-luxurious~ him-father-fashionable~ him-father-classic",
    connectstext: "<img src='https://picsum.photos/seed/casual/200/200' width='100%' />~ <img src='https://picsum.photos/seed/luxurious/200/200' width='100%' />~ <img src='https://picsum.photos/seed/fashionable/200/200' width='100%' />~ <img src='https://picsum.photos/seed/classic/200/200' width='100%' />",
    toolTipText: "Casual~ Luxurious~ Fashionable~ Classic",
    rowNumber: 3,
    nostoId: "",
  },
  {
    slug: "him-father-casual",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/diamonds/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />",
    toolTipText: "Jewellery~ Jewellery~ Jewellery~ Jewellery",
    rowNumber: 4,
    nostoId: "",
  },
  {
    slug: "him-father-luxurious",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/engagement/200/200' width='100%' />~ <img src='https://picsum.photos/seed/rings/200/200' width='100%' />~ <img src='https://picsum.photos/seed/ring/200/200' width='100%' />~ <img src='https://picsum.photos/seed/diamondrings/200/200' width='100%' />",
    toolTipText: "Fashion Watches~ Luxurius Watches~ Luxurius Watches~ Luxurius Watches",
    rowNumber: 4,
    nostoId: "",
  },
  {
    slug: "him-father-fashionable",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/watch/200/200' width='100%' />~ <img src='https://picsum.photos/seed/watches/200/200' width='100%' />~ <img src='https://picsum.photos/seed/fashion/200/200' width='100%' />~ <img src='https://picsum.photos/seed/all/200/200' width='100%' />",
    toolTipText: "Accessories~ Accessories~ Accessories~ Accessories",
    rowNumber: 4,
    nostoId: "",
  },
  {
    slug: "him-father-classic",
    text: "Do you have already an idea?",
    connectsto: "The End~ The End~ The End~ The End",
    connectstext: "<img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />~ <img src='https://picsum.photos/seed/jewellery/200/200' width='100%' />",
    toolTipText: "Inspire Me~ Inspire Me~ Inspire Me~ Inspire Me",
    rowNumber: 4,
    nostoId: "",
  },
  
];